name: KoTH
main: subside.plugins.koth.KothPlugin
version: 1.4.8
author: SubSide
softdepend: [Multiverse-Core, Factions, Kingdoms, LegacyFactions, PlaceholderAPI, VanishNoPacket]
commands:
  koth:
    description: Gives access to koth
permissions:
  koth.*:
    description: Gives the player all the permissions
    children:
      koth.default: true
      koth.admin: true
      koth.control: true
  koth.default:
    description: Gives the player all the default permissions
    children:
      koth.help: true
      koth.list: true
      koth.loot: true
      koth.schedule: true
      koth.version: true
      koth.ignore: true
      koth.next: true
  koth.help:
    description: Gives the player permissions to /koth (help)
    default: true
  koth.ignore:
    description: Allows you to ignore the chat messages
    default: true
  koth.list:
    description: Gives the player permissions to /koth list
    default: true
  koth.loot:
    description: Gives the player permissions to /koth loot
    default: true
  koth.schedule:
    description: Gives the player permissions to /koth schedule
    default: true
  koth.version:
    description: Gives the player permissions to /koth version
    default: true
  koth.next:
    description: Gives the player permissions to /koth next
    default: true

  koth.admin:
    description: Gives access to all admin permissions!
    children:
      koth.admin.create: true
      koth.admin.edit: true
      koth.admin.remove: true
      koth.admin.bypass: true
      koth.admin.help: true
      koth.admin.loot: true
      koth.admin.reload: true
      koth.admin.schedule: true
      koth.admin.info: true
      koth.admin.tp: true
  koth.admin.create:
    description: Gives the player permissions to create koths
    default: op
  koth.admin.edit:
    description: Gives the player permissions to edit koths
    default: op
  koth.admin.remove:
    description: Gives the player permissions to remove koths
    default: op
  koth.admin.bypass:
    description: Gives the player permissions to bypass chest protection
    default: false
  koth.admin.help:
    description: Gives the player permissions to the full help menu
    default: op
  koth.admin.loot:
    description: Gives the player permissions to edit the loot chest
    default: op
    children:
      koth.loot: true
  koth.admin.reload:
    description: Gives the player permissions to reload the plugin
    default: op
  koth.admin.schedule:
    description: Gives the player permissions to schedule koths
    default: op
    children:
      koth.schedule: true
  koth.admin.info:
    description: Gives the player permissions to show info about koths
    default: op
  koth.admin.tp:
    description: Gives the player permissions to tp to koths
    default: op
  koth.admin.admin:
    description: Gives the player permissions to tp to koths
    default: op

  koth.control:
    description: Gives the player permissions to all control commands
    children:
      koth.control.start: true
      koth.control.end: true
      koth.control.stop: true
  koth.control.start:
    description: Gives the player permissions to start koths
    default: op
  koth.control.end:
    description: Gives the player permissions to gracefully end koths
    default: op
  koth.control.stop:
    description: Gives the player permissions to forcefully stop koths
    default: op
